"""Add SoundCloud OAuth fields to users

Revision ID: 584424dda9ee
Revises: 5ab6276b6556
Create Date: 2026-01-10 16:51:06.765901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '584424dda9ee'
down_revision: Union[str, None] = '5ab6276b6556'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('soundcloud_user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('soundcloud_access_token', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('soundcloud_refresh_token', sa.String(length=500), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_soundcloud_user_id'), 'users', ['soundcloud_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_soundcloud_user_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'soundcloud_refresh_token')
    op.drop_column('users', 'soundcloud_access_token')
    op.drop_column('users', 'soundcloud_user_id')
    # ### end Alembic commands ###
