"""add ticket_url and external_id to events

Revision ID: d66f0f4188d4
Revises: 47a5c4dc420e
Create Date: 2026-03-31 15:11:59.743836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd66f0f4188d4'
down_revision: Union[str, None] = '47a5c4dc420e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('ticket_url', sa.String(length=500), nullable=True))
    op.add_column('events', sa.Column('external_id', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'events', ['external_id'])
    op.drop_constraint('uq_users_spotify_user_id', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_users_spotify_user_id', 'users', ['spotify_user_id'])
    op.drop_constraint(None, 'events', type_='unique')
    op.drop_column('events', 'external_id')
    op.drop_column('events', 'ticket_url')
    # ### end Alembic commands ###
