"""add_google_oauth_fields_to_users

Revision ID: f3f1de32e562
Revises: add_venues_fk
Create Date: 2026-02-04 15:34:33.575636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f1de32e562'
down_revision: Union[str, None] = 'add_venues_fk'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_list_items_venue_name', table_name='list_items')
    op.create_unique_constraint('uq_list_set_item', 'list_items', ['list_id', 'set_id'])
    op.alter_column('lists', 'list_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('SETS', 'EVENTS', 'VENUES', 'TRACKS', name='listtype', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'sets'::character varying"))
    op.add_column('users', sa.Column('google_user_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('google_token_expires_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_google_user_id'), 'users', ['google_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_user_id'), table_name='users')
    op.drop_column('users', 'google_token_expires_at')
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'google_user_id')
    op.alter_column('lists', 'list_type',
               existing_type=sa.Enum('SETS', 'EVENTS', 'VENUES', 'TRACKS', name='listtype', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'sets'::character varying"))
    op.drop_constraint('uq_list_set_item', 'list_items', type_='unique')
    op.create_index('ix_list_items_venue_name', 'list_items', ['venue_name'], unique=False)
    # ### end Alembic commands ###
